name: Publish PowerShell Modules
description: Publishes PowerShell module(s) to the PowerShell Gallery
branding:
  icon: upload-cloud
  color: green
inputs:
  ApiKey:
    description: The API Key for pushing to PowerShell Gallery
    required: true
  SkipValidation:
    description: Skip Test-ModuleManifest validation (e.g. issue(s) with RequiredModules that you want to ignore)
    required: false
    default: 'false'
  SkipPublish:
    description: Skip publishing (e.g. if you want to test the module(s) without actually publishing it)
    required: false
    default: 'false'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.ApiKey }}
    - ${{ inputs.SkipValidation }}
    - ${{ inputs.SkipPublish }}
